spring.datasource.url=jdbc:postgresql://localhost:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

opencharge.api.key=${OPEN_CHARGE_API_KEY}

spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true


# Test
# Only show warnings and errors from Spring
logging.level.org.springframework=WARN

# Only show warnings and errors from Tomcat
logging.level.org.apache.catalina=WARN

# Keep your own project's logs at the normal INFO or DEBUG level
logging.level.com.yourprojectname=INFO
# Format: Time | Level | Message
logging.pattern.console=%d{HH:mm:ss} %-5level - %msg%n
# Force colors in the console
spring.output.ansi.enabled=ALWAYS